### ISSUE TITLE
Receive numerous big red atom notifications

### ISSUE THREAD

**Issue by mikeerickson** [nmn/linter-flow-plus#13]
During normal development, these errors popup frequently when coding.   These are new since I added this package and appear to be related to "flow" in general?

![image](https://cloud.githubusercontent.com/assets/183153/20276241/524b3e14-aa50-11e6-9ee4-30ebbb33b700.png)

**Comment by nmn** [comment]
This package is deprecated. Please use `linter-flow`

**Comment by mikeerickson** [comment]
@nmn OK, will do...
