### ISSUE TITLE
Remove from APM?

### ISSUE THREAD

**Issue by keplersj** [nmn/linter-flow-plus#4]
Now that you are maintaining AtomLinter/linter-flow, might want to think about removing this from APM.

**Comment by nmn** [comment]
I have keeping this package alive for now. But once I can figure out the best way to transition people over, I'll sunset this package in favour of linter-flow.

**Comment by steelbrain** [comment]
You could remove the codebase and keep an activate function that adds a notification telling users to install other package. and publish it as an update.

**Comment by nmn** [comment]
cool. I'll do that as the next release.

**Comment by keplersj** [comment]
Where does this issue stand?

**Comment by nmn** [comment]
Sorry, been behind on this. Will end-of-life this package this weekend.

**Comment by keplersj** [comment]
_cough_
