### ISSUE TITLE
Linter Failure on Disjoint Unions

### ISSUE THREAD

**Issue by jasonzoladz** [nmn/linter-flow-plus#6]
This is valid, idiomatic @flow but it shows a linting error:

<img width="875" alt="screen shot 2015-11-01 at 1 18 21 pm" src="https://cloud.githubusercontent.com/assets/8467728/10870539/412a1504-809b-11e5-8920-e06f23bef29c.png">

**Comment by nmn** [comment]
I don't think this is the fault of the linter. Are you sure you have an up-to-date version of flow??

Also, this package is deprecated. Please switch to `linter-flow`
