### ISSUE TITLE
Unpublish from apm?

### ISSUE THREAD

**Issue by Arcanemagus** [nmn/linter-flow-plus#8]
@nmn as it looks like you are maintaining both this and [AtomLinter/linter-flow](https://github.com/AtomLinter/linter-flow), what do you think about unpublishing this repo from APM so you only have to maintain one of them?

**Comment by nmn** [comment]
I'm working on a good migration experience. Just been busy.

**Comment by Arcanemagus** [comment]
Makes sense, just was testing the new Windows binary and saw this package when I searched apm for "flow" :wink:.
