### ISSUE TITLE
Having an issue supressing an error.

### ISSUE THREAD

**Issue by aintnorest** [nmn/linter-flow-plus#9]
I use:

[options]
suppress_comment= \(.\|\n\)*\$FlowIssue

and 
// $FlowIssue
import "styles/Main.css";

But continually get linting error from either that line or the first line in the file. Any thoughts? I also get the error if I do relative pathing instead of using my alias so ./styles/Main.css  . Is there a way to just ignore all imports I'm okay with that as well. This morning I thought about it and felt like maybe i should be putting this request at the core linter level apparently they disagree https://github.com/atom-community/linter/issues/647 . It looks like theres even a pull request to add the feature but they feel like the individual linters should implement it.

**Comment by nmn** [comment]
This is actually a bug in flow itself. It doesn't respect suppress comment when dealing with flow-check-contents.

However, I'm adding a way to make it work in linter-flow soon.

This project is deprecated, please use linter-flow

**Comment by aintnorest** [comment]
Yeah I made a comment asking about the current state of the bug in Flows issues either right before or after I posted this issue. 
I've tried twice now to use linter-flow but it consistently gives me problems. Either with flow crashing and restarting a lot or errors because it's looking in the wrong places like node-modules. Sometimes it just stops checking which I'm guessing is caused by the first problem but if thats the case its only telling me when flow starts up and crashes sometimes.
I know I should put issue requests in but this repo besides that one problem just works for the most part. Also your autocomplete works great as well so I've just stuck with this one. Didn't realize you had depreciated this to work with linter-flow.

**Comment by nmn** [comment]
@aintnorest This is a big reason I didn't get rid of the yet. atom-linter is under active development, with multiple people working on it. This one is now frozen.

That said, a little while ago, when I was asked to contribute to atom-linter, the whole repo was re-written as a clone of this repo. There has been more work done on it since, though.

There were recent problems that have been fixed, so I urge you try atom-linter once more.

**Comment by nmn** [comment]
Switch to Linter-Flow. This is deprecated. Closing.
